import { useAtom, useSetAtom, useAtomValue } from 'jotai/react';
import React, { useState } from 'react';
import {
    isBatchActionsModalOpenAtom,
    batchActionItemsDataAtom,
    userAtom,
    InventoryVersionAtom,
    isCatalogBatchSelectModeAtom,
    catalogBatchSelectedItemsAtom,
} from '../../lib/atoms';
import { supabase } from '../../lib/supabase';
import { BoundingBox2DType } from '../../lib/Types';
import { getCleanImageUrl, loadImage, normalizeInventoryData, resizeImage } from '../../lib/utils';
import { mediaOf, rowOf } from '../../lib/ai/run';
import { useTranslation, useNotify } from '../../lib/hooks';
import { tr } from '../../lib/i18n';
import { MediaOriginNote } from './ItemMediaPanel';
import { processSingleItem, letterboxToUnit, type BatchOp, type PipelineContext, type ProcessId } from '../../lib/catalogHubPipeline';
import { generateJson } from '../../lib/ai/client';
import { aiErrorMessage } from '../../lib/ai/errors';
import { hasGeminiKey } from '../../lib/ai/keys';
import { toPipelineItem } from '../../lib/ai/item';
import { buildDetectionPrompt, type DetectionBox } from '../../lib/ai/prompts';
import { aiResultFromOps, buildAiPatch, saveAiPatch, isEmptyPatch } from '../../lib/ai/persist';
import type { Json } from '../../lib/database.types';



/**
 * The AI actions write the canonical columns through lib/ai/persist, like
 * every other save path. They used to write camelCase keys that are not
 * columns (so PostgREST rejected the first item and the batch stopped), and
 * even mapped they inverted the column map: a sentence into the manual Type,
 * '*' bullets into the HTML column, an HTML body into the title column, and
 * a mask colour over the vendor's `color`. The three text actions are now
 * the Catalog Hub's processes -- title, marketing HTML, colours and type --
 * generated by the same prompt and finished by the same rules.
 */
type ActionType = 'boxes' | 'masks' | 'title' | 'marketing' | 'colorsType' | 'delete';

/** Which CATALOG_PROCESSES each action runs. 'boxes' is not a process; it has its own column. */
const ACTION_PROCESSES: Partial<Record<ActionType, ProcessId[]>> = {
    masks: ['image_segmentation'],
    title: ['title_desc'],
    marketing: ['marketing_desc'],
    colorsType: ['dominant_colors', 'product_type'],
};

export function BatchActionsModal() {
    const t = useTranslation();
    const notify = useNotify();
    const [isOpen, setIsOpen] = useAtom(isBatchActionsModalOpenAtom);
    const [batchActionItems, setBatchActionItems] = useAtom(batchActionItemsDataAtom);
    const user = useAtomValue(userAtom);
    const setInventoryVersion = useSetAtom(InventoryVersionAtom);

    const setIsBatchSelectMode = useSetAtom(isCatalogBatchSelectModeAtom);
    const setBatchSelectedItems = useSetAtom(catalogBatchSelectedItemsAtom);

    const [selectedActions, setSelectedActions] = useState<Set<ActionType>>(new Set());
    const [isProcessing, setIsProcessing] = useState(false);
    const [progress, setProgress] = useState(0);
    const [currentTask, setCurrentTask] = useState('');

    /* `masks` is the one action on this list that produces a PROCESSED image:
       it writes the cutout PNG and outline, which is the frame every other
       catalog surface labels PROCESSED. An operator picking actions for 40
       items could not tell that from "Generate Segmentation Masks", so the
       row says it in the same two words the badges use. */
    const ACTIONS: { id: ActionType, label: string, desc?: string, adminOnly: boolean }[] = [
        { id: 'boxes', label: tr('Generate 2D Boxes'), adminOnly: false },
        {
            id: 'masks',
            label: tr('Generate Segmentation Masks (inc. PNG/SVG)'),
            desc: tr('Produces the PROCESSED image — the background-cleaned frame shown publicly. Leaves the RAW uploads untouched.'),
            adminOnly: false,
        },
        { id: 'title', label: tr('Generate AI Title'), adminOnly: false },
        { id: 'marketing', label: tr('Generate Marketing Description (HTML)'), adminOnly: false },
        { id: 'colorsType', label: tr('Generate Colors & Product Type'), adminOnly: false },
        { id: 'delete', label: t.deleteItems, adminOnly: true },
    ];

    const handleClose = () => {
        if (isProcessing) return;
        setIsOpen(false);
        setBatchActionItems([]);
    };

    const resetAndClose = () => {
        handleClose();
        setBatchSelectedItems([]);
        setIsBatchSelectMode(false);
    };

    const handleActionToggle = (actionId: ActionType) => {
        setSelectedActions(prev => {
            const newSet = new Set(prev);
            if (newSet.has(actionId)) {
                newSet.delete(actionId);
            } else {
                newSet.add(actionId);
            }
            return newSet;
        });
    };

    /**
     * Labelled boxes for spatial_boxes_2d. The photo goes through resizeImage,
     * which letterboxes it with 10% padding, so the model's coordinates are
     * mapped back to the photo itself rather than read as if it filled the frame.
     */
    const runDetection = async (imageUrl: string, item: any): Promise<BoundingBox2DType[]> => {
        const img = await loadImage(imageUrl);
        const base64 = (await resizeImage(imageUrl, 1024)).split(',')[1];
        const { prompt, schema } = buildDetectionPrompt(toPipelineItem(item));
        const boxes = await generateJson<DetectionBox[]>({ job: 'segmentation', prompt, schema, images: [base64] });
        const toUnit = letterboxToUnit(img.width, img.height);
        const clamp = (v: number) => Math.min(1, Math.max(0, v));
        return (Array.isArray(boxes) ? boxes : [])
            .filter(b => Array.isArray(b?.box_2d) && b.box_2d.length === 4)
            .map(b => {
                const a = toUnit([b.box_2d[0], b.box_2d[1]]);
                const z = toUnit([b.box_2d[2], b.box_2d[3]]);
                const x = clamp(a.x), y = clamp(a.y);
                return { x, y, width: clamp(z.x) - x, height: clamp(z.y) - y, label: b.label || 'object' };
            })
            .filter(b => b.width > 0 && b.height > 0);
    };

    const handleDelete = async () => {
        if (!window.confirm(`Are you sure you want to permanently delete ${batchActionItems.length} items? This cannot be undone.`)) return;

        setIsProcessing(true);
        setProgress(0);
        setCurrentTask(`Deleting ${batchActionItems.length} items...`);
        const toastId = notify.loading(currentTask);

        try {
            const inventoryRows = batchActionItems.filter(i => i.data?.status !== 'Production').map(i => i.row);
            const productionRows = batchActionItems.filter(i => i.data?.status === 'Production').map(i => i.row);

            if (inventoryRows.length > 0) {
                const { error } = await supabase.from('inventory').delete().in('id', inventoryRows.map(String));
                if (error) throw error;
            }
            if (productionRows.length > 0) {
                const { error } = await supabase.from('production').delete().in('id', productionRows.map(String));
                if (error) throw error;
            }

            setProgress(batchActionItems.length);
            notify.success(`Successfully deleted ${batchActionItems.length} items.`, { id: toastId });
            setInventoryVersion(v => v + 1);
            setTimeout(resetAndClose, 1500);

        } catch (error: any) {
            notify.error(`Deletion failed: ${error.message}`, { id: toastId });
        } finally {
            setIsProcessing(false);
        }
    }

    const handleStart = async () => {
        if (selectedActions.has('delete')) {
            await handleDelete();
            return;
        }
        if (!hasGeminiKey()) {
            notify.error(tr("No Gemini API key is set"));
            return;
        }

        const processes = new Set<ProcessId>();
        selectedActions.forEach(a => (ACTION_PROCESSES[a] || []).forEach(p => processes.add(p)));
        const wantBoxes = selectedActions.has('boxes');

        const totalItems = batchActionItems.length;
        setIsProcessing(true);
        setProgress(0);
        const toastId = notify.loading(tr("Starting batch process..."));

        // One failed item no longer stops the batch, and there are no fixed
        // 10 s / 20 s sleeps: every request takes a slot from the shared
        // limiter (lib/ai/limiter), which is what those sleeps approximated.
        const failures: string[] = [];
        for (let i = 0; i < batchActionItems.length; i++) {
            const item = batchActionItems[i];
            const itemLabel = `${item.data.shape} #${item.data.itemNumber}`;
            const progressLabel = `(${i + 1}/${totalItems})`;
            const say = (task: string) => {
                setCurrentTask(`${task} ${itemLabel} ${progressLabel}...`);
                notify.loading(`${task} ${itemLabel} ${progressLabel}...`, { id: toastId });
            };

            try {
                // The AI columns exist on inventory only.
                if (item.data?.status === 'Production' || item.source === 'production') {
                    throw new Error('Production rows have no AI columns');
                }
                const rowId = String(item.row);
                // The row's own first photo, as the run engine reads it. Not
                // item.imageUrl: the catalogue card shows generated_png_url
                // there first, and running on that would cut out the cutout
                // and save it over the hero's.
                const firstStill = mediaOf(normalizeInventoryData(rowOf(item))).find(m => !m.isVideo)?.url;
                const imageUrl = getCleanImageUrl(firstStill || '');
                if (!imageUrl) throw new Error('Could not load item image.');

                let boxes: BoundingBox2DType[] | null = null;
                if (wantBoxes) {
                    say(tr('Generating boxes for'));
                    boxes = await runDetection(imageUrl, item);
                }

                const op: BatchOp = {
                    id: `bam_${rowId}`,
                    item,
                    imageUrl,
                    imageIndex: 0,
                    status: 'idle',
                    progress: 0,
                    logs: [],
                    processes,
                    // 'cloud': the model labels the parts (and traces a
                    // mirror's glass) and the local contour cuts the piece --
                    // the closest of the four modes to what this action did.
                    processingMode: 'cloud',
                    result: {},
                };
                if (processes.size > 0) {
                    say(tr('Processing'));
                    const ctx: PipelineContext = {
                        updateOp: (_id, updates) => { Object.assign(op, typeof updates === 'function' ? updates(op) : updates); },
                        logOp: (_id, text) => { op.logs = [...op.logs, text]; },
                        checkAbort: async (_id, promise) => await promise,
                        user,
                        bgQuality: '2K',
                        cancelTokens: { current: {} },
                        setHasUnsavedChanges: () => {},
                    };
                    await processSingleItem(op, ctx);
                }

                say(tr('Saving data for'));
                const { data: stored, error: readErr } = await supabase.from('inventory').select('*').eq('id', rowId).single();
                if (readErr || !stored) throw new Error(readErr?.message || 'Item not found');
                const patch = await buildAiPatch(aiResultFromOps([op]), stored, processes, { user });
                if (boxes) patch.columns.spatial_boxes_2d = boxes as unknown as Json;
                if (!isEmptyPatch(patch)) await saveAiPatch(rowId, patch, { user });

                // What the pipeline could not do, or an upload the writer had
                // to leave out, is a failure of this item, even when the rest
                // of it saved.
                const failedSteps = [...Object.values(op.processErrors || {}), ...patch.failedUploads];
                if (failedSteps.length) failures.push(`${itemLabel}: ${failedSteps.join('; ')}`);
                else if (op.status === 'failed') failures.push(`${itemLabel}: ${op.logs.filter(l => l.includes('[ FAIL ]')).pop() || 'failed'}`);
            } catch (error: any) {
                failures.push(`${itemLabel}: ${aiErrorMessage(error)}`);
            }
            setProgress(i + 1);
        }

        setInventoryVersion(v => v + 1);
        setIsProcessing(false);
        if (failures.length === 0) {
            notify.success(`Batch process completed for ${totalItems} items!`, { id: toastId });
            setTimeout(resetAndClose, 1500);
        } else {
            notify.error(`${totalItems - failures.length}/${totalItems} done. ${failures.slice(0, 3).join(' | ')}${failures.length > 3 ? ' ...' : ''}`, { id: toastId, duration: 12000 });
        }
    };

    if (!isOpen) return null;

    const availableActions = ACTIONS.filter(a => !a.adminOnly || user?.role === 'Admin');
    const totalItems = batchActionItems.length;

    const pct = totalItems > 0 ? Math.round((progress / totalItems) * 100) : 0;

    /* This modal is portalled at the app shell, outside the #catalog root, so
       its own root carries .catalog-hub. The scrim is a compound selector
       (`.catalog-hub.cat-scrim`), hence both classes on the same element. */
    return (
        <div className="catalog-hub cat-scrim">
            <div className="cat-modal" role="dialog" aria-modal="true" aria-label={t.batchActionsTitle(totalItems)}>
                <div className="cat-head">
                    <h2 className="cat-title">{t.batchActionsTitle(totalItems)}</h2>
                </div>
                <hr className="cat-rule" />
                <div className="cat-modal-body">
                    {isProcessing ? (
                        /* An instrument: pressed, mono, tabular. The native
                           <progress> could not be given the module's well, and
                           its percentage was proportional-figure text that
                           jittered as it counted. */
                        <div className="cat-progress" role="status" aria-live="polite">
                            <p className="cat-progress-task">{currentTask}</p>
                            <div
                                className="cat-progress-track"
                                role="progressbar"
                                aria-valuemin={0}
                                aria-valuemax={totalItems}
                                aria-valuenow={progress}>
                                <div className="cat-progress-fill" style={{ width: `${pct}%` }} />
                            </div>
                            <span className="cat-progress-n">{progress} / {totalItems} · {pct}%</span>
                        </div>
                    ) : (
                        <>
                            <p className="cat-sub">{t.batchActionsPrompt}</p>
                            {availableActions.map(action => (
                                <label key={action.id} className="cat-action">
                                    <input
                                        type="checkbox"
                                        name="batchAction"
                                        value={action.id}
                                        checked={selectedActions.has(action.id)}
                                        onChange={() => handleActionToggle(action.id)} />
                                    <span className="min-w-0">
                                        <span className="cat-action-t">{action.label}</span>
                                        {action.desc && <span className="cat-action-d">{action.desc}</span>}
                                    </span>
                                </label>
                            ))}
                            {/* The rule in words, said once on this surface too. */}
                            <MediaOriginNote />
                        </>
                    )}
                </div>
                <div className="cat-modal-foot">
                    <button type="button" onClick={handleClose} className="cat-key cat-key--quiet" disabled={isProcessing}>{t.cancel}</button>
                    <button type="button" onClick={handleStart} className="cat-key" disabled={isProcessing || selectedActions.size === 0}>
                        {isProcessing ? t.processing : `${t.start} (${selectedActions.size})`}
                    </button>
                </div>
            </div>
        </div>
    );
}